- name: slave testing and installation playbook
  hosts: slave
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
          name:
            - apt-transport-https
            - ca-certificates
            - lsb-release
            - gnupg
          state: latest
          update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
          url: "https://download.docker.com/linux/ubuntu/gpg"
          state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
          repo: "deb https://download.docker.com/linux/ubuntu focal stable"
          state: present
          filename: docker

    - name: Install Docker
      ansible.builtin.apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
          state: latest
          update_cache: true